title: Pawnsy
description: "Social Media Chess Platform for Del Norte High School"
owner_name: Nikhil Maturi
github_username: code259
github_repo: "sprint4_frontend"
baseurl: "/sprint4_frontend" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/create_and_compete/reality-game.md
  - navigation/game.md
  - navigation/analysis.md
  - navigation/manager.md
  - navigation/skills.md
  - navigation/leaderboard.md